# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxIbb73gNuK0fDPCuoPeoFkh8Lx_vGyn
"""

#multiply all the item in a list
lst=[3,5,7,8]
for num in lst:
  a=3*5*7*8
print("multiplication of all the num in alst:",a)

#List
#sum of all item in a list
lst=[2,4,5,8,9]
a=sum(lst)
print("sum of all number present in the lst:",a)

#Write a Python program to get the largest number from a list
lst=[4,8,5,7,6]
a=max(lst)
print("largest number from the list:",a)

#Write a Python program to get the smallest number from a list.
lst=[3,5,6,8]
a=min(lst)
print("smallest number from the lst:",a)

#Write a  Python program to remove duplicates from a list.
lst=[4,5,6,4,6,6]
a=set(lst)
print("remove duplicates from the lst:",a)

#Write a Python program to check if a list is empty or not.
lst=[]
if not lst:
  print("list is empty")
else:
  print("lst is not empty")

#Write a Python program to clone or copy a list.
org_lst=[4,5,6,7,8]
new_lst=lst.copy()
print("org_lst:",org_lst)
print("new_lst:",org_lst)

#Write a Python function that takes two lists and returns True if they have at least one common member.
lst1=[3,4,5,6]
lst2=[2,3,7,8,9]
for num in lst1:
  if num in lst2:
    print("true")
  else:
    print("false")

# Write a Python program to shuffle and print a specified list.
lst=[4,5,6,7,8]
import random
random.shuffle(lst)
print("Shuffle list:",lst)

#Write a Python program to select the odd items from a list.
lst=[2,3,4,5,6,7,8]
for num in lst:
  if num%2!=0:
    print("odd number:",num)

#pop element from the list
lst=[2,3,4,5]
lst.pop(3)
print(lst)

